#!/Library/Frameworks/Python.framework/Versions/3.5/bin/python3

# Execute program in python

inputArguments = sys.argv

if (sys.argv[1] == "--help")
{
  print("usage: scrum [<file-path>] [--help]")
}
